GET https://localhost:3000/plants
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "korisnik",
    "password": "lozinka"
}

###

POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "korisnik5",
    "password": "lozinka5",    
    "email": "email"
}

###
GET http://localhost:3000/progress
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

###
GET http://localhost:3000/plants
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

###
POST http://localhost:3000/plants/insert
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "name": "Cherry rajčica",
    "summary": "Ove male sočne rajčice najpopularnija su sorta rajčica kada je u pitanju uzgoj na balkonu. Često su ukusnije od većih rajčica, ali i skuplje.",
    "difficulty": "Prigodno za početnike",
    "category": "Povrće",
    "owner": "Coffein++",
    "care": "Kada cherry rajčice uzgajate u teglama, omogućite im dosta sunčeve svjetlosti jer ako budu u sjeni, slabo će se razviti i neće biti dovoljno plodova. Najbolje ih je izložiti sunčevom svjetlu šest do osam sati dnevno.",
    "instructions": "Ako vam je prvi put da sadite rajčice, najbolje bi bilo da krenete od presadnica. Pri odabiru presadnica, vodite računa o njihovoj kvaliteti i zdravlju, a najbolje je da ih kupite na tržnici ili od provjerenog prodavača. Posudu u koju ćete posaditi rajčicu trebate do pola napuniti kompostom i zemljom, zatim staviti presadnicu zajedno s korijenom i zemljom.",
    "duration": "40-60"
}

###
POST http://localhost:3000/plantComments/byId
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "plantId": 1,
    "userId": 1,
    "comment": "hello world"
}

###
DELETE http://localhost:3000/plantComments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "commentId": "550ce09e-5612-44b4-ae02-7098b8de267e"
}

###
PATCH http://localhost:3000/progress/stageId
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "progressId": 1,
    "stageId": 2
}

###
PATCH http://localhost:3000/progress/stageStartedOn
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "progressId": 1
}

###
PATCH http://localhost:3000/progress/lastWateredOn
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "progressId": 1
}

###
PATCH http://localhost:3000/progress/done
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "progressId": 1,
    "done": false
}

###
POST http://localhost:3000/plants/byId
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "plantId": 1
}

###
GET http://localhost:3000/growthStages
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

###
POST http://localhost:3000/growthStages/byId
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "growthStageId": 1
}

###
GET http://localhost:3000/growthConditions
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

###
POST http://localhost:3000/growthConditions/byId
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "growthConditionsId": 1
}

###
GET http://localhost:3000/materials
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

###
DELETE https://afternoon-depths-99413.herokuapp.com/deleteAccount
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "username": "Cc",
    "password": "cc"
}

###
DELETE http://localhost:3000/deleteAccount
Content-Type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia29yaXNuaWsiLCJpYXQiOjE1ODYzOTMwODJ9.mGC4iKLRuul3fpFYEvEr6AmnshvqlTXFYYhKW4pHwbE

{
    "username": "a",
    "password": "a"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "a",
    "password": "a",    
    "email": "a"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "a",
    "password": "a"
}

###
GET http://localhost:3000/senzori


